### PR TITLE
Fix multiple spaces replacement in classlist

### PR DESCRIPTION
**Pull request by Davilarek**

### CODE REVIEW

**Comment by zrodevkaan** [comment]
Requesting this as soon as I closed my macbook smh.

Give me an example of why this change was needed?

**Comment by Davilarek** [comment]
`648875` has `textBadge` which contains two spaces in a class list.
```js
648875: function(e) {
        "use strict";
        e.exports = {
        	// . . .
        	textBadge: "textBadge_f05120 base__5ed84 eyebrow_c15ff6",
        	// . . .
        }
},
```
without this PR it evaluates to
```css
.textBadge_f05120.base__5ed84 eyebrow_c15ff6 {
    
}
```
and with this PR:
```css
.textBadge_f05120.base__5ed84.eyebrow_c15ff6 {
    
}
```
let me know if this PR may have any side effects

**Comment by zrodevkaan** [comment]
Ahh gotcha. Do you want this regex approach or do you wanna just use `replaceAll`

**Comment by Davilarek** [comment]
`replaceAll` is not highlighted by my code editor so I prefer this

**Comment by zrodevkaan** [comment]
alright lol

**Pull request merged**
